import { jsPDF } from "jspdf";
import "jspdf-autotable";
import { ExamResult, Quiz } from "../types";

/**
 * Utility to convert image URL to Base64 for PDF placement
 */
const getBase64ImageFromURL = (url: string): Promise<string> => {
  return new Promise((resolve, reject) => {
    const img = new Image();
    img.setAttribute("crossOrigin", "anonymous");
    img.onload = () => {
      const canvas = document.createElement("canvas");
      canvas.width = img.width;
      canvas.height = img.height;
      const ctx = canvas.getContext("2d");
      ctx?.drawImage(img, 0, 0);
      const dataURL = canvas.toDataURL("image/png");
      resolve(dataURL);
    };
    img.onerror = (error) => reject(error);
    img.src = url;
  });
};

export const generateQuizReport = async (quiz: Quiz, results: ExamResult[], logoUrl?: string) => {
  const doc = new jsPDF();
  const timestamp = new Date().toLocaleString();
  const examDate = quiz.scheduledDate ? new Date(quiz.scheduledDate).toLocaleDateString() : new Date().toLocaleDateString();

  let yPos = 20;

  if (logoUrl) {
    try {
      const base64Logo = await getBase64ImageFromURL(logoUrl);
      doc.addImage(base64Logo, "PNG", 95, 12, 20, 20);
      yPos = 42;
    } catch (e) {
      yPos = 30;
    }
  }

  doc.setFontSize(22);
  doc.setTextColor(30, 41, 59);
  doc.setFont("helvetica", "bold");
  doc.text("COUNCIL SOLUTIONS NEPAL", 105, yPos, { align: 'center' });
  
  yPos += 8;
  doc.setFontSize(10);
  doc.setTextColor(100);
  doc.setFont("helvetica", "normal");
  doc.text("OFFICIAL COHORT PERFORMANCE TRANSCRIPT", 105, yPos, { align: 'center' });

  yPos += 12;
  doc.setDrawColor(226, 232, 240);
  doc.setLineWidth(0.5);
  doc.line(14, yPos, 196, yPos);
  
  yPos += 10;
  doc.setFontSize(10);
  doc.setTextColor(71, 85, 105);
  
  doc.setFont("helvetica", "bold");
  doc.text("PROGRAM:", 14, yPos);
  doc.setFont("helvetica", "normal");
  doc.text(quiz.program.toUpperCase(), 40, yPos);

  doc.setFont("helvetica", "bold");
  doc.text("EXAM DATE:", 120, yPos);
  doc.setFont("helvetica", "normal");
  doc.text(examDate, 150, yPos);

  yPos += 6;
  doc.setFont("helvetica", "bold");
  doc.text("ASSESSMENT:", 14, yPos);
  doc.setFont("helvetica", "normal");
  doc.text(quiz.title.toUpperCase(), 45, yPos);

  yPos += 8;
  doc.line(14, yPos, 196, yPos);

  const tableData = results.map((res, index) => [
    index + 1,
    res.userName.toUpperCase(),
    res.score,
    res.totalQuestions,
    `${res.percentage.toFixed(1)}%`,
    res.percentage >= 80 ? 'DISTINCTION' : res.percentage >= 50 ? 'PASS' : 'FAIL'
  ]);

  (doc as any).autoTable({
    startY: yPos + 10,
    head: [['Rank', 'Practitioner Name', 'Marks', 'Total', 'Mastery', 'Status']],
    body: tableData,
    theme: 'grid',
    headStyles: { fillColor: [30, 41, 59], textColor: [255, 255, 255], fontStyle: 'bold', halign: 'center' },
    styles: { fontSize: 9, cellPadding: 4 },
    columnStyles: { 0: { halign: 'center' }, 2: { halign: 'center' }, 3: { halign: 'center' }, 4: { halign: 'center' }, 5: { halign: 'center', fontStyle: 'bold' } },
    alternateRowStyles: { fillColor: [248, 250, 252] },
  });

  const pageCount = (doc as any).internal.getNumberOfPages();
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i);
    doc.setFontSize(8);
    doc.setTextColor(148, 163, 184);
    doc.text(`Generated by CSN System Node: ${timestamp}`, 14, 285);
    doc.text(`Page ${i} of ${pageCount}`, 105, 285, { align: 'center' });
    doc.text(`Verification ID: ${quiz.id.substring(0,8).toUpperCase()}`, 196, 285, { align: 'right' });
  }

  doc.save(`CohortReport_${quiz.program.replace(/\s+/g, '_')}_${Date.now()}.pdf`);
};

export const generateIndividualTranscript = async (quiz: Quiz, result: ExamResult, logoUrl?: string) => {
  const doc = new jsPDF();
  const timestamp = new Date().toLocaleString();

  // 1. Header & Logo
  if (logoUrl) {
    try {
      const base64Logo = await getBase64ImageFromURL(logoUrl);
      doc.addImage(base64Logo, "PNG", 14, 15, 25, 25);
    } catch (e) {}
  }

  doc.setFontSize(24);
  doc.setTextColor(37, 99, 235); // blue-600
  doc.setFont("helvetica", "bold");
  doc.text("COUNCIL SOLUTIONS NEPAL", 45, 25);
  
  doc.setFontSize(10);
  doc.setTextColor(100);
  doc.setFont("helvetica", "normal");
  doc.text("OFFICIAL INDIVIDUAL EVALUATION RECORD", 45, 32);

  // 2. Student Info Box
  doc.setDrawColor(200);
  doc.rect(14, 50, 182, 40);
  doc.setFontSize(12);
  doc.setTextColor(30, 41, 59);
  doc.setFont("helvetica", "bold");
  doc.text("PRACTITIONER IDENTITY", 20, 60);
  
  doc.setFontSize(10);
  doc.setFont("helvetica", "normal");
  doc.text(`Name: ${result.userName.toUpperCase()}`, 20, 70);
  doc.text(`Program: ${result.program}`, 20, 78);
  doc.text(`Council: ${result.council}`, 20, 86);
  
  doc.text(`Examination Date: ${new Date(result.timestamp).toLocaleDateString()}`, 110, 70);
  doc.text(`Node Reference: ${result.id.substring(0,10).toUpperCase()}`, 110, 78);

  // 3. Performance Breakdown
  doc.setFontSize(14);
  doc.setFont("helvetica", "bold");
  doc.text("ASSESSMENT SUMMARY", 14, 110);
  doc.setFontSize(10);
  doc.setFont("helvetica", "normal");
  doc.text(quiz.title.toUpperCase(), 14, 116);

  (doc as any).autoTable({
    startY: 125,
    head: [['Component', 'Result']],
    body: [
      ['Items Correct', result.score.toString()],
      ['Total Evaluation Items', result.totalQuestions.toString()],
      ['Mastery Percentage', `${result.percentage.toFixed(2)}%`],
      ['Academic Status', result.percentage >= 50 ? 'SATISFACTORY' : 'UNSATISFACTORY']
    ],
    theme: 'striped',
    headStyles: { fillColor: [37, 99, 235] },
    columnStyles: { 0: { fontStyle: 'bold', cellWidth: 80 } }
  });

  // 4. Authenticity Seal
  doc.setDrawColor(37, 99, 235);
  doc.setLineWidth(1);
  doc.circle(170, 230, 20);
  doc.setFontSize(8);
  doc.text("OFFICIAL", 170, 227, { align: 'center' });
  doc.text("CSN NEPAL", 170, 233, { align: 'center' });
  doc.text("VERIFIED", 170, 239, { align: 'center' });

  // 5. Footer
  doc.setFontSize(8);
  doc.setTextColor(150);
  doc.text(`This is a computer-generated transcript synchronized with the CSN Cloud Node. No signature required.`, 105, 275, { align: 'center' });
  doc.text(`Report Generated: ${timestamp}`, 105, 282, { align: 'center' });

  doc.save(`Transcript_${result.userName.replace(/\s+/g, '_')}_${Date.now()}.pdf`);
};